###getBooksList заглушка
POST http://localhost:8080/__admin/mappings
Content-Type: application/json

{
  "name": "getBooksListTest",
  "request": {
    "method": "POST",
    "url": "/getBooksList",
    "headers": {
      "x-trace-id": {
        "equalTo": "123UFC"
      }
    }
  },
  "response": {
    "headers": {
      "Content-Type": "application/json"
    },
    "status": 200,
    "jsonBody": {
      "bookData": [
        {
          "id": 122334567,
          "renter": "ФИО",
          "rentalStartTime": "23.06.2022 17:42:36",
          "rentalStopTime": "25.06.2022 07:41:30",
          "title": "Сборник стихов",
          "publisher": "Издательство",
          "recommendationIdList": [123, 8347843, 6543893],
          "contentData": [
            {
              "description": "Стих про зиму",
              "title": "Зимнее утро",
              "author": "Пушкин А.С.",
              "category": "poem",
              "recommendationIdList": [311749, 1234, 54323]
            }
          ]
        }
      ]
    }
  }
}

###uploadBook заглушка
POST http://localhost:8080/__admin/mappings
Content-Type: application/json

{
  "name": "uploadBookTest",
  "request": {
    "method": "POST",
    "url": "/uploadBook",
    "headers": {
      "x-trace-id": {
        "equalTo": "123UFC"
      }
    }
  },
  "response": {
    "headers": {
      "Content-Type": "application/json"
    },
    "status": 200,
    "jsonBody": {
      "status_code": 0,
      "id": 122334567,
      "date_of_upload": "23.06.2023 20:22:36"
    }
  }
}

###updateRecommendation заглушка
POST http://localhost:8080/__admin/mappings
Content-Type: application/json

{
  "name": "updateRecommendationTest",
  "request": {
    "method": "PATCH",
    "url": "/updateRecommendation",
    "headers": {
      "x-trace-id": {
        "equalTo": "123UFC"
      }
    }
  },
  "response": {
    "headers": {
      "Content-Type": "application/json"
    },
    "status": 200
  }
}

###
POST http://localhost:8081/getBooksList
Content-Type: application/json
x-trace-id: 123UFC

        {
            "searchAttributes": [
                {
                    "searchAttribute": "id",
                    "value": "12345",
                    "searchType": "EQUAL"
                },
                {
                    "searchAttribute": "title",
                    "value": "Сборник стихов",
                    "searchType": "EQUAL"
                },
                {
                    "searchAttribute": "rentalStartTime",
                    "value": "2023-04-18T00:00:00+03:00,2023-05-18T23:00:00+03:00",
                    "searchType": "BETWEEN"
                },
   {
                    "searchAttribute": "rentalStopTime",
                    "value": "2023-05-18T00:00:00+03:00,2023-05-16T00:00:00+03:00",
                    "searchType": "BETWEEN"
                },
                {
                    "searchAttribute": "renter",
                    "value": "",
                    "searchType": "NOT_EMPTY"
                }
            ]
}
### Заглушка для проверки обновления рекоммендаций 1.
POST http://localhost:8080/__admin/mappings
Content-Type: application/json

{
  "name": "getBooksListTest1",
  "request": {
    "method": "POST",
    "url": "/getBooksList",
    "headers": {
      "x-trace-id": {
        "equalTo": "123UFC"
      }
    },
    "bodyPatterns": [
      {
        "matchesJsonPath": "$.searchAttributes[?(@.attribute == 'publisher' && @.value == 'Издатель1')]"
      }
    ]
  },
  "response": {
    "headers": {
      "Content-Type": "application/json"
    },
    "status": 200,
    "jsonBody": {
      "bookData": [
        {
          "id": 1,
          "renter": "John Doe",
          "rentalStartTime": "28.06.2022 12:00:36",
          "rentalStopTime": "30.06.2022 07:41:30",
          "title": "Book 1",
          "publisher": "Издатель1",
          "recommendationIdList": [123, 456],
          "contentData": [
            {
              "description": "Description 1",
              "title": "Title 1",
              "author": "Author 1",
              "category": "Category 1",
              "recommendationIdList": [789, 101112]
            }
          ]
        }
      ]
    }
  }
}

### Заглушка для проверки обновления рекоммендаций 2.
POST http://localhost:8080/__admin/mappings
Content-Type: application/json

{
  "name": "getBooksListTest3",
  "request": {
    "method": "POST",
    "url": "/getBooksList",
    "headers": {
      "x-trace-id": {
        "equalTo": "123UFC"
      }
    },
    "bodyPatterns": [
      {
        "matchesJsonPath": "$.searchAttributes[?(@.attribute == 'publisher' && @.value == 'Издатель2')]"
      }
    ]
  },
  "response": {
    "headers": {
      "Content-Type": "application/json"
    },
    "status": 200,
    "jsonBody": {
      "bookData": [
        {
          "id": 2,
          "renter": "Jane Smith",
          "rentalStartTime": "10.08.2022 02:02:36",
          "rentalStopTime": "30.09.2023 05:01:30",
          "title": "Book 2",
          "publisher": "Издатель2",
          "recommendationIdList": [321, 654],
          "contentData": [
            {
              "description": "Description 2",
              "title": "Title 2",
              "author": "Author 2",
              "category": "Category 2",
              "recommendationIdList": [987, 654]
            }
          ]
        }
      ]
    }
  }
}

###
PATCH http://localhost:8081/updateRecommendation
Content-Type: application/json
x-trace-id: 123UFC

{

}